# configs/config.yaml
data_dir: ./records               
robot_name: franka               
state_topic: robot_state 
capture_interval: 0.001             
writer_pool_max_workers: 8
writer_max_pending_writes: 4096

camera_streams:
  zed_left:
    topic: zed_left    
    recv_timeout_ms: 1000
  zed_right:
    topic: zed_right    
    recv_timeout_ms: 1000
  zed_wrist:
    topic: zed_wrist
    recv_timeout_ms: 1000            
